/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroaluno;

import Controle.IODado;
import Controle.IOIndice;
import Dado.Aluno;
import Controle.IODado;
import Controle.IOIndice;
import java.util.Scanner;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author d119322
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextCPF = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jTextRA = new javax.swing.JTextField();
        jTextIdade = new javax.swing.JTextField();
        jButtonCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextBusca = new javax.swing.JTextField();
        jButtonCadastro1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButtonIndice = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelRemover = new javax.swing.JLabel();
        jButtonRemover = new javax.swing.JButton();
        jTextRemover = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAC_cadastro");
        setName("DacCAD"); // NOI18N

        jTabbedPane1.setToolTipText("Cadastro");
        jTabbedPane1.setName("Cadastro"); // NOI18N

        jButtonCadastro.setText("Cadastrar");
        jButtonCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastroMouseClicked(evt);
            }
        });

        jLabel1.setText("Aguardando");

        jLabel4.setText("Nome");

        jLabel5.setText("RA");

        jLabel6.setText("Idade");

        jLabel7.setText("CPF");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextRA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCPF)
                            .addComponent(jTextIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(163, 163, 163))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(154, 154, 154))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButtonCadastro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastro)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jTextBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscaActionPerformed(evt);
            }
        });

        jButtonCadastro1.setText("Buscar");
        jButtonCadastro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastro1MouseClicked(evt);
            }
        });

        jLabel2.setText("Resultado: ");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Nome", "CPF", "RA" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastro1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jButtonCadastro1))))
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("Busca", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Coluna 1", "Coluna 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Nome", "CPF", "RA" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jButtonIndice.setLabel("Buscar");
        jButtonIndice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIndiceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonIndice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButtonIndice))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Indice", jPanel3);

        jLabel3.setText("Insira o RA do registro a ser deletado:");

        jLabelRemover.setText("Aguardando.");
        jLabelRemover.setToolTipText("");

        jButtonRemover.setLabel("Remover");
        jButtonRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabelRemover))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButtonRemover))
                            .addComponent(jLabel3))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemover)
                    .addComponent(jTextRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelRemover)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remover", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Cadastro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastroMouseClicked
        // TODO add your handling code here:
        IODado arquivo = new IODado("src\\dados.txt");
        
        
        //Escrita nos indices
        IOIndice indiceRA = new IOIndice("src\\indiceRA.txt");
        indiceRA.escreverIndP(jTextRA.getText()+'|'+arquivo.getTam());
        IOIndice indiceNome = new IOIndice("src\\IndiceSec.txt");
        indiceNome.escreverIndP(jTextNome.getText()+'|'+jTextRA.getText());
        IOIndice indiceCPF = new IOIndice("src\\indiceCPF.txt");
        indiceCPF.escreverIndP(jTextCPF.getText()+'|'+arquivo.getTam());
        //Escrita no Arquivo
        arquivo.escrever(jTextRA.getText()+"|"+jTextNome.getText()+"|"+jTextIdade.getText()+"|"+jTextCPF.getText()+"#");
        
        jTextRA.setText("");
        jTextNome.setText("");
        jTextIdade.setText("");
        jTextCPF.setText("");
        jLabel1.setText("Cadastrado!");
        
        arquivo.finalizar();
    }//GEN-LAST:event_jButtonCadastroMouseClicked

    private void jButtonCadastro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastro1MouseClicked
        // TODO add your handling code here:
        String aux;
        IODado arquivo = new IODado("src\\dados.txt");
        Aluno aux1 = new Aluno();
        long time1;
        long time2;
        long time3;
        
        switch(jList1.getSelectedIndex()){
            case 0:
                time1 = System.nanoTime();
                IOIndice indiceNome = new IOIndice("src\\IndiceSec.txt");
                IOIndice indiceRA1 = new IOIndice("src\\indiceRA.txt");
                
                aux = indiceNome.busca(jTextBusca.getText());
                aux= indiceRA1.busca(aux);
                jLabel2.setText(aux);
                if(aux!=null){
                    aux1 = arquivo.ler(Long.parseLong(aux));
                    time2 = System.nanoTime();
                    jLabel2.setText("<html>"+
                            "RA: "+aux1.getRA()+"<br />"+
                            "Nome: "+aux1.getNome()+"<br />"+
                            "CPF: "+aux1.getCPF()+"<br />"+
                            "Idade: "+aux1.getIdade() +                           
                            "<br />Tempo de consulta: " + (time2 - time1)/1000+" milissegundos.</html>");
                }else{
                    time3 = System.nanoTime();
                    
                    jLabel2.setText("<html>Não encontrado!" + "<br />Tempo de consulta: " + (time3 - time1)/1000+" milissegundos.</html>");
                }
                break;
            case 1:
                time1 = System.nanoTime();
                IOIndice indiceCPF = new IOIndice("src\\indiceCPF.txt");
                
                aux = indiceCPF.busca(jTextBusca.getText());
                jLabel2.setText(aux);
                if(aux!=null){
                    aux1 = arquivo.ler(Long.parseLong(aux));
                    time2 = System.nanoTime();
                    jLabel2.setText("<html>"+
                            "RA: "+aux1.getRA()+"<br />"+
                            "Nome: "+aux1.getNome()+"<br />"+
                            "CPF: "+aux1.getCPF()+"<br />"+
                            "Idade: "+aux1.getIdade() +                           
                            "<br />Tempo de consulta: " + (time2 - time1)/1000+" milissegundos.</html>");
                }else{
                    time3 = System.nanoTime();
                    
                    jLabel2.setText("<html>Não encontrado!<br />Tempo de consulta: " + (time3 - time1)/1000+" milissegundos.</html>");
                }
                break;
            case 2:
                time1 = System.nanoTime();
                IOIndice indiceRA = new IOIndice("src\\indiceRA.txt");
                
                aux = indiceRA.busca(jTextBusca.getText());
                jLabel2.setText(aux);
                if(aux!=null){
                    aux1 = arquivo.ler(Long.parseLong(aux));
                    time2 = System.nanoTime();
                    jLabel2.setText("<html>"+
                            "RA: "+aux1.getRA()+"<br />"+
                            "Nome: "+aux1.getNome()+"<br />"+
                            "CPF: "+aux1.getCPF()+"<br />"+
                            "Idade: "+aux1.getIdade() +                           
                            "<br />Tempo de consulta: " + (time2 - time1)/1000+" milissegundos.</html>");
                }else{
                    time3 = System.nanoTime();
                    
                    jLabel2.setText("<html>Não encontrado!<br />Tempo de consulta: " + (time3 - time1)/1000+" milissegundos.</html>");
                }
                break;
            default:
                jLabel2.setText("Selectione uma opção e clique no botão buscar.");
                break;
        }
            
        
        
    }//GEN-LAST:event_jButtonCadastro1MouseClicked

    private void jTextBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscaActionPerformed

    private void jButtonRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoverMouseClicked
        // TODO add your handling code here:
        String aux_IniDado;
        IODado arquivo = new IODado("src\\dados.txt");
        Aluno aux1 = new Aluno();
        
        
        IOIndice indiceRA = new IOIndice("src\\indiceRA.txt");
        IOIndice indiceNome = new IOIndice("src\\IndiceSec.txt");  
        IOIndice indiceCPF = new IOIndice("src\\indiceCPF.txt");
        
        aux_IniDado = indiceRA.busca(jTextRemover.getText());
                
                if(aux_IniDado!=null){
                    aux1 = arquivo.ler(Long.parseLong(aux_IniDado));
                    indiceRA.atualiza(aux1.getRA());
                    indiceCPF.atualiza(aux1.getCPF());
                    indiceNome.atualiza(aux1.getNome());
                    arquivo.atualiza(Long.parseLong(aux_IniDado));
                    jLabelRemover.setText("Removido!");
                    arquivo.finalizar();
                }else{
                   
                    jLabelRemover.setText("Dado não encontrado!");
                    arquivo.finalizar();
                }
                
    }//GEN-LAST:event_jButtonRemoverMouseClicked

    private void jButtonIndiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIndiceMouseClicked
        // TODO add your handling code here:
        IOIndice indiceRA = new IOIndice("src\\indiceRA.txt");
        IOIndice indiceNome = new IOIndice("src\\IndiceSec.txt");  
        IOIndice indiceCPF = new IOIndice("src\\indiceCPF.txt");
        String[] aux;
        int i = 0;
        
        switch(jList2.getSelectedIndex()){
            case 0:
                jTable1.getColumnModel().getColumn(0).setHeaderValue("Nome");
                jTable1.getColumnModel().getColumn(1).setHeaderValue("RA");
                jTable1.getTableHeader().resizeAndRepaint();
                //jTable1.add({aux[0],aux[1]});
                while(indiceNome.getPos()<indiceNome.getTam()){
                    aux = indiceNome.lerLinha(indiceNome.getPos());
                    jTable1.setValueAt(aux[0], i, 0);
                    jTable1.setValueAt(aux[1], i, 1);
                    i++;
                }
                break;
                
            case 1:
                jTable1.getColumnModel().getColumn(0).setHeaderValue("CPF");
                jTable1.getColumnModel().getColumn(1).setHeaderValue("Posicao");
                jTable1.getTableHeader().resizeAndRepaint();
                //jTable1.add({aux[0],aux[1]});
                while(indiceCPF.getPos()<indiceCPF.getTam()){
                    aux = indiceCPF.lerLinha(indiceCPF.getPos());
                    jTable1.setValueAt(aux[0], i, 0);
                    jTable1.setValueAt(aux[1], i, 1);
                    i++;
                }
                break;
                
            case 2:
                jTable1.getColumnModel().getColumn(0).setHeaderValue("RA");
                jTable1.getColumnModel().getColumn(1).setHeaderValue("Posicao");
                jTable1.getTableHeader().resizeAndRepaint();
                //jTable1.add({aux[0],aux[1]});
                while(indiceRA.getPos()<indiceRA.getTam()){
                    aux = indiceRA.lerLinha(indiceRA.getPos());
                    jTable1.setValueAt(aux[0], i, 0);
                    jTable1.setValueAt(aux[1], i, 1);
                    i++;
                }
                break;
                
            default:
                jLabel2.setText("Selectione uma opção e clique no botão buscar.");
                break;
        }
        indiceRA.finalizar();
    }//GEN-LAST:event_jButtonIndiceMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonCadastro1;
    private javax.swing.JButton jButtonIndice;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelRemover;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBusca;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextIdade;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextRA;
    private javax.swing.JTextField jTextRemover;
    // End of variables declaration//GEN-END:variables
}
